spring:
  application:
    name: SpringJPA
  datasource:
    url: jdbc:h2:mem:player;DB_CLOSE_EXIT=FALSE;
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
