server:
  port: 5432
spring:
  datasource:
    url: jdbc:h2:mem:playerdb
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2